### ISSUE TITLE
Docker heathcheck support

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-web#13]
Implement Docker heathcheck support similar to how we already have them for cli and db containers.

**Comment by sergey-zabolotny** [comment]
Healtcheck support already added.
https://github.com/docksal/service-web/blob/develop/apache2.2/Dockerfile
https://github.com/docksal/service-web/blob/develop/apache2.4/Dockerfile

or you mean somthing else?

**Comment by lmakarov** [comment]
Yep, missed that. Resolved via #11. Thanks
